services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-with-docker
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8000:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock